defaults:
  - _self_
  - plcc
  - rag
  - bug_localization
  - sweep

# ! Uncomment this if you want to use multitask on multi-GPU
#  - override hydra/launcher: joblib
#hydra:
#  launcher:
#    n_jobs: 6

limit: -1