rag:
  model: "deepseek-ai/deepseek-coder-1.3b-base"
  top_k: -1
  splitter: "word_splitter" #["word_splitter", "model_tokenizer", "line_splitter"]
  scorer: "bm25" # ["bm25", "iou"]
  chunker: "fixed_line" #["full_file", "fixed_line"]
  use_n_grams: true
  n_grams_min: 1
  n_grams_max: 1
  chunk_lines_size: 64 #[8, 16, 32, 64, 128]
  stride: null # -> stride size
  set_stride: False
  completion_last_chunk_size: 32
  chunk_completion_file: False