hydra:
    mode: MULTIRUN
    sweeper:
        params:
          ++rag.splitter: model_tokenizer #, line_splitter # word_splitter, model_tokenizer, line_splitter
          ++rag.scorer: iou #, bm25
          ++rag.n_grams_max: 1 #, 2 #, 3